"""Generalized document-level cleanup for OCR/PDF extracted Markdown.

Design goals
------------
* Never discard arbitrary document ranges because of where a section appears.
* Prefer local, evidence-based cleanup over novel-specific sequence assumptions.
* Preserve unknown content and unknown headings by default.
* Allow explicit section exclusion by heading name without deleting later sections.
* Remove picture OCR only when it is very likely to be extraction noise.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Iterable

from ..core.config import require_bool
from ..core.stage import PipelineStage, StageResult
from ..markdown.markdown import BlockType
from .headings import (
    ATX_HEADING,
    BACK_MATTER_HEADING,
    BARE_NUMBERED_HEADING,
    NAMED_HEADING,
    NUMBERED_HEADING,
    SETEXT_UNDERLINE,
    START_HEADING,
    looks_like_false_heading,
    normalize_headings,
    normalize_setext_headings,
    plain_heading_text,
)
from .markup import (
    HTML_BREAK,
    HTML_COMMENT,
    PICTURE_BLOCK,
    UNDERLINE_TAG,
    normalize_inline_markup as _normalize_inline_markup,
)
from .paragraphs import (
    SECTION_NUMBER,
    is_heading,
    is_list_or_special,
    looks_structured_lines,
    reconstruct_paragraphs,
    should_join,
    split_overlong_paragraph,
)
from .picture_ocr import (
    clean_picture_block,
    filter_picture_ocr,
    picture_text_is_readable,
)
from .protection import protect_markdown
from .sections import (
    FOOTNOTE_DEFINITION,
    FOOTNOTE_REFERENCE,
    FRONT_MATTER_SIGNALS,
    GLOSSARY_FOOTNOTE,
    LOCAL_METADATA_HEADINGS,
    METADATA_LINE_PATTERNS,
    NARRATIVE_SECTION,
    SIGNUP_OR_NEWSLETTER,
    TRAILING_TOC_ITEM,
    remove_bounded_glossary_footnotes,
    remove_generic_publisher_tail,
    remove_leading_front_matter,
    remove_local_metadata,
    remove_named_sections,
    remove_promotional_tail,
    section_key as _section_key,
)
from .text_normalization import (
    DECORATIVE_SEPARATOR_LINE,
    find_conservative_ocr_noise,
    normalize_spacing,
    strip_markdown_emphasis,
)


@dataclass
class _Change:
    """Describe one document-level transformation for change reporting.

    The dataclass decorator generates the methods used by this internal value
    object. Construction through ``__init__`` accepts the reason and text
    excerpts, with confidence defaulting to 99 percent::

        change = _Change(
            reason="Removed newsletter tail",
            before="Sign up for the Yen Press Newsletter",
            after="",
        )
        assert change.confidence == 99.0

    The generated ``__repr__`` provides a diagnostic representation suitable
    for logs and debugging::

        repr(_Change("Normalized heading", "Chapter 1", "# Chapter 1", 98.0))

    The generated ``__eq__`` compares every field, which is useful in focused
    cleanup tests::

        assert _Change("Removed comment", "<!--x-->", "") == _Change(
            "Removed comment", "<!--x-->", ""
        )

    Instances are collected during whole-document processing and later copied
    into the shared change tracker; they do not mutate Markdown themselves.

    Example:
        ``instance = _Change("Safe correction", "teh", "the")``
        Expected behavior: Describe one document-level transformation for change reporting.
    """

    reason: str
    """Human-readable explanation of why the transformation was appropriate."""

    before: str
    """Small source excerpt or summary representing content before cleanup."""

    after: str
    """Replacement excerpt or summary representing content after cleanup."""

    confidence: float = 99.0
    """Percentage confidence attached to the transformation's audit record."""


_Change.__init__.__doc__ = """Initialize one pending document-cleanup record.

Args:
    reason: Human-readable explanation for the transformation.
    before: Source excerpt or summary before cleanup.
    after: Replacement excerpt or summary after cleanup.
    confidence: Percentage certainty; defaults to ``99.0``.

Example::

    change = _Change(
        reason="Removed converter comment",
        before="<!-- generated by converter -->",
        after="",
        confidence=100.0,
    )

The initializer only stores audit information. It does not modify the source
Markdown or write to the shared change tracker.
"""

_Change.__repr__.__doc__ = """Return a developer-readable representation.

Example::

    change = _Change("Normalized heading", "Chapter 1", "# Chapter 1", 98.0)
    print(repr(change))
    # _Change(reason='Normalized heading', before='Chapter 1',
    #         after='# Chapter 1', confidence=98.0)

The representation exposes all fields, which makes a pending transformation
easy to inspect in a debugger or failed test.
"""

_Change.__eq__.__doc__ = """Compare two pending changes field by field.

Example::

    first = _Change("Removed comment", "<!--x-->", "")
    second = _Change("Removed comment", "<!--x-->", "")
    assert first == second
    assert first != _Change("Removed comment", "<!--y-->", "")

Equality includes ``reason``, ``before``, ``after``, and ``confidence``. It is
primarily useful for precise assertions in cleanup tests.
"""


class DocumentCleanupStage(PipelineStage):
    """Reconstruct document structure before segment-level OCR correction.

    This first pipeline stage works on the complete Markdown string because
    front matter, contents pages, picture-OCR blocks, headings, and excluded
    sections require context across paragraph boundaries. It conservatively
    removes recognized non-narrative material, normalizes headings and wrapped
    paragraphs, and reports suspicious whole-document OCR noise without
    deleting it.

    Workflow::

        filter picture OCR -> remove converter comments/front matter
        -> recognize the narrative start -> remove configured sections/tails
        -> normalize headings and emphasis -> reconstruct paragraphs
        -> report residual OCR-noise findings -> rebuild context segments

    Example:
        ``instance = DocumentCleanupStage(config)``
        Expected behavior: Reconstruct document structure before segment-level OCR correction.
    """

    name = "DocumentCleanup"
    config_section = "cleanup"

    @staticmethod
    def _apply_text_transform(
        text: str,
        changes: list[_Change],
        transform: Callable[[str], str],
        *,
        reason: str,
        before: str,
        after: str,
        confidence: float = 99.0,
    ) -> str:
        """Apply a transform and append its audit record only when it changes text.

        Centralizing this invariant keeps the document workflow readable and
        prevents a transform from being applied without a matching report.
        Transforms that return counters or classifications remain explicit in
        :meth:`process`.
        """
        transformed = transform(text)
        if transformed != text:
            changes.append(_Change(reason, before, after, confidence))
        return transformed

    def process(self, context) -> StageResult:
        """Clean the complete document and rebuild its editable segments.

        Every material transformation is appended to the shared tracker. OCR
        noise detection is explicitly report-only: findings count as records,
        but their source text remains untouched for human review.

        Returns:
            A result whose change count includes transformations and report-only
            findings recorded by this stage.

        Example::

            stage = DocumentCleanupStage(config)
            result = stage.execute(context)
            cleaned = context.get_markdown()

        If ``context`` contains copyright front matter followed by ``# Prologue``,
        the front matter is removed, the narrative is retained, and ``result``
        reports the corresponding audit records.
        """
        text = context.current_markdown or context.original_markdown
        changes: list[_Change] = []
        text = self._apply_text_transform(
            text,
            changes,
            self._normalize_setext_headings,
            reason="Normalized Setext headings to ATX Markdown",
            before="Setext headings",
            after="ATX headings",
        )
        remove_footnotes = self.config.get_bool(
            "cleanup.remove_footnotes",
            True,
        )
        remove_glossary_footnotes = self.config.get_bool(
            "cleanup.remove_glossary_footnotes",
            True,
        )

        def cleanup_block(block) -> bool:
            if (
                remove_glossary_footnotes
                and block.block_type is BlockType.BLOCKQUOTE
            ):
                lines = [
                    line for line in block.content.splitlines() if line.strip()
                ]
                return bool(lines and GLOSSARY_FOOTNOTE.match(lines[0]))
            return False

        protected = protect_markdown(
            text,
            cleanup_block=cleanup_block,
            protect_footnote_identifiers=not remove_footnotes,
        )
        text = protected.text

        excluded = self.config.get(
            "cleanup.excluded_sections",
            [
                "Afterword",
                "Aferword",
                "Character Profiles",
                "Character Profile",
                "Character Profles",
                "Character Profle",
            ],
        )

        picture_mode = str(self.config.get("cleanup.picture_ocr_mode", "safe")).lower()
        # Backward compatibility with the old boolean option.
        if not self.config.get_bool("cleanup.remove_picture_ocr", True):
            picture_mode = "keep"
        text, removed_count, preserved_count = self._filter_picture_ocr(
            text,
            mode=picture_mode,
            excluded_sections=excluded,
        )
        if removed_count:
            changes.append(
                _Change(
                    "Removed likely picture-OCR noise",
                    f"{removed_count} noisy picture OCR block(s)",
                    "",
                    97.0,
                )
            )
        if preserved_count:
            changes.append(
                _Change(
                    "Preserved readable picture-OCR content",
                    f"{preserved_count} readable picture OCR block(s)",
                    "text retained",
                    99.0,
                )
            )

        # Residual non-picture comments are converter markup, not content.
        text = self._apply_text_transform(
            text,
            changes,
            lambda value: HTML_COMMENT.sub("", value),
            reason="Removed residual converter HTML comments",
            before="converter HTML comments",
            after="",
            confidence=100.0,
        )

        if self.config.get_bool("cleanup.remove_front_matter", True):
            text = self._apply_text_transform(
                text,
                changes,
                self._remove_leading_front_matter,
                reason=(
                    "Removed strongly identified leading cover/publication "
                    "front matter"
                ),
                before="cover/navigation/publication prefix",
                after="",
                confidence=98.0,
            )

        if self.config.get_bool("cleanup.remove_front_matter", True):
            text = self._apply_text_transform(
                text,
                changes,
                self._remove_local_metadata,
                reason=(
                    "Removed local publication metadata without "
                    "sequence-based truncation"
                ),
                before="metadata blocks/lines",
                after="",
                confidence=96.0,
            )

        if excluded:
            text, removed_sections = self._remove_named_sections(text, excluded)
            if removed_sections:
                changes.append(
                    _Change(
                        "Removed explicitly configured sections only",
                        ", ".join(removed_sections),
                        "",
                        99.0,
                    )
                )

        if self.config.get_bool("cleanup.remove_promotional_tail", True):
            text = self._apply_text_transform(
                text,
                changes,
                self._remove_promotional_tail,
                reason="Removed publisher next-volume promotional tail",
                before="coming-soon preview",
                after="",
                confidence=98.0,
            )

        if remove_glossary_footnotes:
            text, removed_glossary = self._remove_bounded_glossary_footnotes(text)
            if removed_glossary:
                changes.append(
                    _Change(
                        "Removed bounded bare/blockquoted glossary footnotes",
                        f"{removed_glossary} glossary footnote block(s)",
                        "",
                        98.0,
                    )
                )

        if self.config.get_bool("cleanup.remove_publisher_tail", True):
            text, tail_kind = self._remove_generic_publisher_tail(text)
            if tail_kind:
                changes.append(
                    _Change(
                        f"Removed trailing {tail_kind}",
                        "publisher/navigation tail",
                        "",
                        98.0,
                    )
                )

        text = self._apply_text_transform(
            text,
            changes,
            lambda value: DECORATIVE_SEPARATOR_LINE.sub("", value),
            reason="Removed standalone decorative separator lines",
            before="ornamental symbol separators",
            after="",
        )

        if remove_footnotes:
            new, count = FOOTNOTE_DEFINITION.subn("", text)
            new = FOOTNOTE_REFERENCE.sub("", new)
            if count or new != text:
                changes.append(
                    _Change(
                        "Removed Markdown footnotes",
                        "footnotes present",
                        "footnotes removed",
                        95.0,
                    )
                )
                text = new

        text = self._apply_text_transform(
            text,
            changes,
            _normalize_inline_markup,
            reason="Normalized residual HTML/Markdown markup",
            before="legacy inline markup",
            after="normalized markup",
        )

        text = self._apply_text_transform(
            text,
            changes,
            self._normalize_headings,
            reason="Normalized structural headings",
            before="irregular headings",
            after="normalized Markdown headings",
        )

        hyphen_setting = self.config.get(
            "regex.corrections.broken_hyphen_words", True
        )
        if isinstance(hyphen_setting, dict):
            hyphen_setting = hyphen_setting.get("enabled", True)
        preserve_hyphen_line_breaks = (
            self.config.get_bool("regex.enabled", True)
            and require_bool(
                hyphen_setting,
                "regex.corrections.broken_hyphen_words.enabled",
            )
        )
        text = self._apply_text_transform(
            text,
            changes,
            lambda value: self._reconstruct_paragraphs(
                value,
                # Dictionary/context validation happens later in SymSpell.
                dehyphenate=False,
                preserve_hyphen_line_breaks=preserve_hyphen_line_breaks,
            ),
            reason="Reconstructed PDF/OCR wrapped paragraphs",
            before="split paragraph lines",
            after="joined prose paragraphs",
            confidence=96.0,
        )

        if self.config.get_bool("cleanup.strip_markdown_emphasis", True):
            text = self._apply_text_transform(
                text,
                changes,
                self._strip_markdown_emphasis,
                reason="Removed Markdown emphasis markers for TTS",
                before="Markdown emphasis",
                after="plain text",
            )

        text = self._apply_text_transform(
            text,
            changes,
            self._normalize_spacing,
            reason="Normalized whitespace and blank lines",
            before="irregular whitespace",
            after="normalized whitespace",
        )

        text = protected.restore(text)

        if text != context.current_markdown:
            context.replace_markdown(text)

        for item in changes:
            context.tracker.add(
                stage=self.name,
                block_index=-1,
                segment_index=-1,
                line=0,
                before=item.before,
                after=item.after,
                confidence=item.confidence,
                reason=item.reason,
            )

        noise_findings = []
        if self.config.get_bool("cleanup.report_ocr_noise", True):
            noise_findings = self._find_conservative_ocr_noise(
                text,
                limit=int(self.config.get("cleanup.ocr_noise_report_limit", 100)),
            )
            for line_number, line, reason in noise_findings:
                context.tracker.add(
                    stage="OCRNoiseReview",
                    block_index=-1,
                    segment_index=-1,
                    line=line_number,
                    before=line,
                    after=line,
                    confidence=0.0,
                    reason=f"Report only; text was preserved: {reason}",
                )

        return StageResult(stage=self.name, changes=len(changes) + len(noise_findings))

    # ------------------------------------------------------------------
    # Picture OCR
    # ------------------------------------------------------------------
    @staticmethod
    def _clean_picture_block(block: str) -> str:
        """Remove picture-OCR wrappers and normalize their extracted text.

        Example:
            ``_clean_picture_block("<!-- Start of picture text -->Map<br>Gate"
            "<!-- End of picture text -->")`` returns ``"Map\nGate"``.
        """
        return clean_picture_block(block)

    @staticmethod
    def _picture_text_is_readable(text: str) -> bool:
        """Conservative readability heuristic for OCR extracted from images.

        Sufficiently language-like captions, maps, profile cards, and diagrams
        are retained. Short labels may require ``picture_ocr_mode: keep``.
        Blocks dominated by punctuation/single-character fragments are removed.

        Example:
            ``_picture_text_is_readable("Map of the Northern Kingdom Capital")``
            returns ``True``, whereas ``_picture_text_is_readable("\\ / } : ~~")``
            returns ``False``.
        """
        return picture_text_is_readable(text)

    @classmethod
    def _filter_picture_ocr(
        cls,
        text: str,
        mode: str = "safe",
        excluded_sections: Iterable[str] | None = None,
    ) -> tuple[str, int, int]:
        """Filter picture OCR without relying on document sequence.

        Modes:
        * ``keep``: preserve every picture OCR block as cleaned text.
        * ``remove``: remove every picture OCR block.
        * ``safe`` (default): preserve readable blocks, remove likely gibberish.

        Example:
            ``cleaned, removed, preserved = _filter_picture_ocr(source, "safe")``
            preserves a readable map caption but removes a symbol-only OCR block;
            the two counters describe those decisions.
        """
        return filter_picture_ocr(
            text,
            mode=mode,
            excluded_sections=excluded_sections,
            normalize_headings=cls._normalize_headings,
            section_key=_section_key,
        )

    # ------------------------------------------------------------------
    # Local metadata / explicit section exclusion
    # ------------------------------------------------------------------
    @staticmethod
    def _plain_heading_text(line: str) -> str | None:
        """Return normalized text when a line is structurally heading-like.

        Example:
            ``_plain_heading_text("### <u>Afterword</u>")`` returns
            ``"Afterword"``; ``_plain_heading_text("She walked home.")`` returns
            ``None`` because ordinary prose is not promoted.
        """
        return plain_heading_text(line)

    @classmethod
    def _remove_leading_front_matter(cls, text: str) -> str:
        """Remove a leading cover/publication prefix only when evidence is strong.

        This never truncates content after the first real narrative section. It
        exists for OCR/ebook conversions where cover text, reader navigation,
        copyright boilerplate, and publisher data appear before the first
        Prologue/Chapter/Story heading without clean Markdown section markers.

        Example:
            Given ``"Copyright\nYen Press\n\n# Prologue\nStory"``, the returned
            text begins at ``# Prologue``. A normal preface lacking at least two
            publication signals is preserved.
        """
        return remove_leading_front_matter(
            text,
            heading_resolver=cls._plain_heading_text,
        )

    @classmethod
    def _remove_local_metadata(cls, text: str) -> str:
        """Remove clearly identified metadata sections/lines wherever they occur.

        Plain headings such as ``Copyright`` and ``Contents`` are recognized even
        when the converter did not emit Markdown heading markers.

        Example:
            ``"Copyright\nISBN: 123\n# Chapter 1\nStory"`` becomes
            ``"# Chapter 1\nStory"``. Later unrelated sections remain intact.
        """
        return remove_local_metadata(
            text,
            heading_resolver=cls._plain_heading_text,
        )

    @classmethod
    def _remove_named_sections(
        cls, text: str, names: Iterable[str]
    ) -> tuple[str, list[str]]:
        """Remove explicitly named sections locally, regardless of document order.

        Example:
            Removing ``["Afterword"]`` from ``"# Chapter 1\nStory\n# Afterword\n"
            "Notes\n# Appendix\nData"`` returns text containing the chapter and
            appendix plus ``["Afterword"]`` as the removed-heading list.
        """

        return remove_named_sections(
            text,
            names,
            heading_resolver=cls._plain_heading_text,
        )

    @classmethod
    def _remove_promotional_tail(cls, text: str) -> str:
        """Remove a next-volume promotional tail identified by strong local evidence.

        A normal use of the phrase "coming soon" in story prose is untouched.
        Removal only happens when a Volume heading is followed within a few lines
        by publisher-style "Coming soon" text, which is characteristic of ebook
        previews appended after the actual novel.

        Example:
            ``"Story ending.\n\n# Volume 14\nComing soon!"`` becomes
            ``"Story ending."``. Narrative dialogue that merely says
            ``"The train is coming soon"`` is preserved.
        """
        return remove_promotional_tail(
            text,
            heading_resolver=cls._plain_heading_text,
        )

    @staticmethod
    def _remove_bounded_glossary_footnotes(text: str) -> tuple[str, int]:
        """Remove only paragraphs explicitly shaped like numbered glossary notes.

        Example:
            ``_remove_bounded_glossary_footnotes("Story.\n\n1 **Mage** Magic user")``
            returns ``("Story.\n\n", 1)``. ``"1. Ordinary list item"`` is not
            removed because it lacks the bounded bold-term form.
        """
        return remove_bounded_glossary_footnotes(text)

    @staticmethod
    def _remove_generic_publisher_tail(text: str) -> tuple[str, str | None]:
        """Remove strongly identified newsletter or numbered-TOC material at EOF.

        Example:
            A final ``"Sign up for the Yen Press Newsletter"`` is removed and
            returns reason ``"publisher signup/newsletter tail"``. With no
            recognized tail, the original text and ``None`` are returned.
        """
        return remove_generic_publisher_tail(text)

    @staticmethod
    def _find_conservative_ocr_noise(
        text: str,
        *,
        limit: int = 100,
    ) -> list[tuple[int, str, str]]:
        """Find high-signal OCR garbage without changing document text.

        Example:
            ``_find_conservative_ocr_noise("Story\nbcdfghjklmnpqrst")`` returns a
            finding for line 2 with a consonant-cluster reason. The input string
            itself is never rewritten.
        """
        return find_conservative_ocr_noise(text, limit=limit)

    # ------------------------------------------------------------------
    # Heading normalization
    # ------------------------------------------------------------------
    @staticmethod
    def _normalize_setext_headings(text: str) -> str:
        """Convert parsed Setext headings before separator cleanup runs."""
        return normalize_setext_headings(text)

    @staticmethod
    def _normalize_headings(text: str) -> str:
        """Promote real headings, demote false ones, and standardize ATX levels.

        Example:
            ``_normalize_headings("Chapter 2 | Dawn")`` returns
            ``"# Chapter 2: Dawn"``. A converter artifact such as
            ``"## then—"`` is demoted to narrative text.
        """
        return normalize_headings(text)

    @staticmethod
    def _looks_like_false_heading(body: str) -> bool:
        """Detect only high-confidence converter-created prose headings.

        Example:
            ``_looks_like_false_heading("then—")`` returns ``True`` while
            ``_looks_like_false_heading("World Building Notes")`` returns
            ``False``, preserving an unknown but plausible heading.
        """
        return looks_like_false_heading(body)

    # ------------------------------------------------------------------
    # Paragraph reconstruction
    # ------------------------------------------------------------------
    @staticmethod
    def _is_heading(block: str) -> bool:
        """Return whether an entire block is an ATX Markdown heading.

        Example:
            ``_is_heading("## Appendix")`` is ``True`` and
            ``_is_heading("Appendix")`` is ``False``.
        """
        return is_heading(block)

    @staticmethod
    def _is_list_or_special(block: str) -> bool:
        """Return whether a block contains structure that must retain line breaks.

        Example:
            ``_is_list_or_special("- First item")`` and
            ``_is_list_or_special("> Quotation")`` return ``True``; ordinary
            prose returns ``False``.
        """
        return is_list_or_special(block)

    @staticmethod
    def _looks_structured_lines(lines: list[str]) -> bool:
        """Preserve blocks that look like records/cards/tables rather than prose.

        Example:
            ``_looks_structured_lines(["Name: Alice", "Class: Mage"])`` returns
            ``True`` so reconstruction retains the line boundary between fields.
        """
        return looks_structured_lines(lines)

    @classmethod
    def _should_join(cls, left: str, right: str) -> bool:
        """Decide whether adjacent OCR blocks are fragments of one paragraph.

        Example:
            ``_should_join("A curious", "sight appeared.")`` returns ``True``.
            ``_should_join("A sentence ended.", "A new paragraph.")`` returns
            ``False`` because the left fragment has terminal punctuation.
        """
        return should_join(
            left,
            right,
            heading_predicate=cls._is_heading,
            special_predicate=cls._is_list_or_special,
        )

    @staticmethod
    def _split_overlong_paragraph(text: str, max_chars: int = 1800) -> list[str]:
        """Split exceptionally long reconstructed prose at sentence boundaries.

        This is a safety valve for OCR sources that contain thousands of words
        with no blank paragraph separators. Normal-sized paragraphs are left
        untouched. No text is discarded.

        Example:
            ``_split_overlong_paragraph("One sentence. Two sentences.", 15)``
            returns multiple chunks split at sentence or whitespace boundaries;
            joining their text recovers every source word.
        """
        return split_overlong_paragraph(text, max_chars=max_chars)

    @classmethod
    def _reconstruct_paragraphs(
        cls,
        text: str,
        *,
        dehyphenate: bool = True,
        preserve_hyphen_line_breaks: bool = False,
    ) -> str:
        """Join wrapped OCR fragments while preserving structured blocks.

        Example:
            ``_reconstruct_paragraphs("A curious\n\nsight appeared.")`` returns
            ``"A curious sight appeared."``. Headings, lists, quotations, and
            record-like lines retain their structural boundaries.
        """
        return reconstruct_paragraphs(
            text,
            dehyphenate=dehyphenate,
            preserve_hyphen_line_breaks=preserve_hyphen_line_breaks,
            heading_predicate=cls._is_heading,
            special_predicate=cls._is_list_or_special,
            structured_predicate=cls._looks_structured_lines,
            join_predicate=cls._should_join,
            paragraph_splitter=cls._split_overlong_paragraph,
        )

    @staticmethod
    def _strip_markdown_emphasis(text: str) -> str:
        """Remove emphasis delimiters while preserving internal underscores.

        Example:
            ``_strip_markdown_emphasis("_quiet_ **voice** file_name")`` returns
            ``"quiet voice file_name"``.
        """
        return strip_markdown_emphasis(text)

    @staticmethod
    def _normalize_spacing(text: str) -> str:
        """Normalize horizontal whitespace, blank lines, and punctuation spacing.

        Example:
            ``_normalize_spacing("Hello   , world.\n\n\nNext")`` returns
            ``"Hello, world.\n\nNext\n"`` while retaining Markdown heading
            markers and ending the document with one newline.
        """
        return normalize_spacing(text)
